name: CI

on:
  push:
    branches:
      - main

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Pint
        run: ./vendor/bin/pint --test
  versioning:
    name: Create New Version
    needs: [code-style]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Plugins
        run: npm i @semantic-release/changelog @semantic-release/git @semantic-release/exec -D
      - name: Create Release
        run: npx semantic-release@^20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
